#Datastructure types

# Built-in Data structure


1. Built-in Data structure

* List
* Dictionary
* Tuple
* Set

2. User-defined Data structure
* Stack
* Queue
* Tree
* Graph


## Lists
Python Lists are ordered collections of data just like arrays in other programming languages. It allows different types of elements in the list. The costly operation is inserting or deleting the element from the beginning of the List as all the elements are needed to be shifted. Insertion and deletion at the end of the list can also become costly in the case where the preallocated memory becomes full.

In [ ]:
# Creating a List with
# the use of multiple values
List = ["Hills", "Rock", "Trees",5]
print("\nList containing multiple values: ")
print(List)

# Creating a Multi-Dimensional List
# (By Nesting a list inside a List)
List2 = [['OFF', 'ON'], ['Constant']]
print("\nMulti-Dimensional List: ")
print(List2)

# accessing a element from the
# list using index number
print("Accessing element from the list")
print(List[0])
print(List[2])

# accessing a element using
# negative indexing
print("Accessing element using negative indexing")
	
# print the last element of list
print(List[-1])
	
# print the third last element of list
print(List[-3])



List containing multiple values: 
['Hills', 'Rock', 'Trees', 5]

Multi-Dimensional List: 
[['OFF', 'ON'], ['Constant']]
Accessing element from the list
Hills
Trees
Accessing element using negative indexing
5
Rock


## Tuple
Python tuples are similar to lists but Tuples are immutable in nature i.e. once created it cannot be modified. Just like a List, a Tuple can also contain elements of various types.

In Python, tuples are created by placing a sequence of values separated by ‘comma’ with or without the use of parentheses for grouping of the data sequence. 

Note: To create a tuple of one element there must be a trailing comma. For example, (8,) will create a tuple containing 8 as the element.

In [ ]:
# Creating a Tuple with
# the use of Strings
Tuple = ('Close', 'Open')
print("\nTuple with the use of String: ")
print(Tuple)
	
# Creating a Tuple with
# the use of list
list1 = [1, 2, 4, 5, 6]
print("\nTuple using List: ")
Tuple = tuple(list1)

# Accessing element using indexing
print("First element of tuple")
print(Tuple[0])

# Accessing element from last
# negative indexing
print("\nLast element of tuple")
print(Tuple[-1])

print("\nThird last element of tuple")
print(Tuple[-3])



Tuple with the use of String: 
('Close', 'Open')

Tuple using List: 
First element of tuple
1

Last element of tuple
6

Third last element of tuple
4


##Set
Python set is a mutable collection of data that does not allow any duplication. Sets are basically used to include membership testing and eliminating duplicate entries. The data structure used in this is Hashing, a popular technique to perform insertion, deletion, and traversal in O(1) on average. 

If Multiple values are present at the same index position, then the value is appended to that index position, to form a Linked List.

In [ ]:
# Creating a Set with
# a mixed type of values
# (Having numbers and strings)
Set = set([1, 2, 'RAM', 4, 'ROM', 6, 'TB'])
print("\nSet with the use of Mixed Values")
print(Set)

# Accessing element using
# for loop
print("\nElements of set: ")
for i in Set:
	print(i, end =" ")
print()

# Checking the element
# using in keyword
print("TB" in Set)



Set with the use of Mixed Values
{1, 2, 4, 6, 'TB', 'RAM', 'ROM'}

Elements of set: 
1 2 4 6 TB RAM ROM 
True


### Frozen Sets
Frozen sets in Python are immutable objects that only support methods and operators that produce a result without affecting the frozen set or sets to which they are applied. While elements of a set can be modified at any time, elements of the frozen set remain the same after creation.

In [ ]:
# Same as {"a", "b","c"}
normal_set = set(["a", "b","c"])

print("Normal Set")
print(normal_set)

# A frozen set
frozen_set = frozenset(["e", "f", "g"])

print("\nFrozen Set")
print(frozen_set)

# Uncommenting below line would cause error as
# we are trying to add element to a frozen set
# frozen_set.add("h")


Normal Set
{'a', 'b', 'c'}

Frozen Set
frozenset({'g', 'e', 'f'})


## String
Python Strings is the immutable array of bytes representing Unicode characters. Python does not have a character data type, a single character is simply a string with a length of 1.

Note: As strings are immutable, modifying a string will result in creating a new copy.

In [ ]:
String = "Welcome to Google Map"
print("Creating String: ")
print(String)
	
# Printing First character
print("\nFirst character of String is: ")
print(String[0])
	
# Printing Last character
print("\nLast character of String is: ")
print(String[-1])


Creating String: 
Welcome to Google Map

First character of String is: 
W

Last character of String is: 
p


## Dictionary
Python dictionary is an unordered collection of data that stores data in the format of key:value pair. It is like hash tables in any other language with the time complexity of O(1). Indexing of Python Dictionary is done with the help of keys. These are of any hashable type i.e. an object whose can never change like strings, numbers, tuples, etc. We can create a dictionary by using curly braces ({}) or dictionary comprehension.

In [ ]:
# Creating a Dictionary
Dict = {'Name': 'Jhon', 1: [1, 2, 3, 4]}
print("Creating Dictionary: ")
print(Dict)

# accessing a element using key
print("Accessing a element using key:")
print(Dict['Name'])

# accessing a element using get()
# method
print("Accessing a element using get:")
print(Dict.get(1))

# creation using Dictionary comprehension
myDict = {x: x**2 for x in [1,2,3,4,5]}
print(myDict)


Creating Dictionary: 
{'Name': 'Jhon', 1: [1, 2, 3, 4]}
Accessing a element using key:
Jhon
Accessing a element using get:
[1, 2, 3, 4]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


## Matrix
A matrix is a 2D array where each element is of strictly the same size. To create a matrix we will be using the

In [ ]:
import numpy as np

a = np.array([[1,2,3,4],[4,55,1,2],
			[8,3,20,19],[11,2,22,21]])
m = np.reshape(a,(4, 4))
print(m)

# Accessing element
print("\nAccessing Elements")
print(a[1])
print(a[2][0])

# Adding Element
m = np.append(m,[[1, 15,13,11]],0)
print("\nAdding Element")
print(m)

# Deleting Element
m = np.delete(m,[1],0)
print("\nDeleting Element")
print(m)


[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]]

Accessing Elements
[ 4 55  1  2]
8

Adding Element
[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]

Deleting Element
[[ 1  2  3  4]
 [ 8  3 20 19]
 [11  2 22 21]
 [ 1 15 13 11]]


## Bytearray
Python Bytearray gives a mutable sequence of integers in the range 0 <= x < 256.

In [ ]:
# Creating bytearray
a = bytearray((12, 8, 25, 2))
print("Creating Bytearray:")
print(a)

# accessing elements
print("\nAccessing Elements:", a[1])

# modifying elements
a[1] = 3
print("\nAfter Modifying:")
print(a)

# Appending elements
a.append(30)
print("\nAfter Adding Elements:")
print(a)


Creating Bytearray:
bytearray(b'\x0c\x08\x19\x02')

Accessing Elements: 8

After Modifying:
bytearray(b'\x0c\x03\x19\x02')

After Adding Elements:
bytearray(b'\x0c\x03\x19\x02\x1e')


## Array
An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array).
For simplicity, we can think of an array a fleet of stairs where on each step is placed a value (let’s say one of your friends). Here, you can identify the location of any of your friends by simply knowing the count of the step they are on. Array can be handled in Python by a module named array. They can be useful when we have to manipulate only a specific data type values. A user can treat lists as arrays. However, user cannot constraint the type of elements stored in a list. If you create arrays using the array module, all elements of the array must be of the same type. 

In [ ]:
# Python program to demonstrate
# Creation of Array

# importing "array" for array creations
import array as arr

# creating an array with integer type
a = arr.array('i', [1, 2, 3])

# printing original array
print ("The new created array is : ", end =" ")
for i in range (0, 3):
	print (a[i], end =" ")
print()

# creating an array with float type
b = arr.array('d', [2.5, 3.2, 3.3])

# printing original array
print ("The new created array is : ", end =" ")
for i in range (0, 3):
	print (b[i], end =" ")
	


The new created array is :  1 2 3 
The new created array is :  2.5 3.2 3.3 

# User-defined Data structure

## Hash Table

Hash tables are a type of data structure in which the address or the index value of the data element is generated from a hash function. That makes accessing the data faster as the index value behaves as a key for the data value. In other words Hash table stores key-value pairs but the key is generated through a hashing function.

So the search and insertion function of a data element becomes much faster as the key values themselves become the index of the array which stores the data.

In Python, the Dictionary data types represent the implementation of hash tables. The Keys in the dictionary satisfy the following requirements.

The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result for each unique value supplied to the hash function.

The order of data elements in a dictionary is not fixed.

In [4]:
# Declare a dictionary 
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'}

# Accessing the dictionary with its key
print (dict['Name'] , dict['Name'])

dict['School'] = "DPS School"; # Add new entry
print (dict['Age'], dict['Age'])
print (dict['School'], dict['School'])

del dict['Name']; # remove entry with key 'Name'
dict.clear();     # remove all entries in dict
del dict ; 

Zara Zara
7 7
DPS School DPS School


##**Stack**
* Works on the basis of Last-In-First-Out (LIFO) principle.
* Elements can be pushed, accessed & popped as required.
*  Elements are accessed only from the top position.

Functions associate with stack with time complexity for each function is **O**(1)
- push( ) - insert element
- pop( ) - remove element
- size( ) - length of stack
- top( ) - reference to last element
- empty( ) - returns true for empty sack


In [ ]:
# stack implementation using list having time complexity is O(n)
stack=[]
stack.append("This is")
stack.append("Python")
stack.append("Data")
stack.append("Structure")
stack.append("and Algorithms")
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)

['This is', 'Python', 'Data', 'Structure', 'and Algorithms']
and Algorithms
['This is', 'Python', 'Data', 'Structure']
Structure
['This is', 'Python', 'Data']


In [ ]:
# stack implementation using collection deque having time complexity is O(1)
from collections import deque
stack=deque()
stack.append("This is")
stack.append("Python")
stack.append("Data")
stack.append("Structure")
stack.append("and Algorithms")
print(stack)
print(stack.pop())
print(stack)
print(stack.pop())
print(stack)

deque(['This is', 'Python', 'Data', 'Structure', 'and Algorithms'])
and Algorithms
deque(['This is', 'Python', 'Data', 'Structure'])
Structure
deque(['This is', 'Python', 'Data'])


Functions associate with stack with time complexity for each function is O(1)

- put( ) - insert element
- get( ) - remove element
- qsize( ) - size of queue
- full( ) - returns true when queue is full
- empty( ) - returns true for empty
- maxsize( ) - maximun no of elements allowed

In [ ]:
# stack implementation using queue 

from queue import LifoQueue

stack = LifoQueue(maxsize=4)
stack.put("This is")
# stack.put("Python")
stack.put("Data")
stack.put("Structure")
stack.put("and Algorithms")
print(stack.qsize() )
print(stack.full())
stack.get()

stack.get()
print(stack.full())



4
True
False


##**Queue**
* Works on the basis of First-In-First-Out (FIFO) principle.
* queues have both Head & Tail sections.
* operations can beperformed from both the head & the tail.

Functions associate with queue with time complexity for each function is O(1)

- enqueue( ) - insert element at top
- dequeue( ) - removes top element
- peekfirst( ) - get 1st element
- peeklast( ) - get last element
- display( ) - print element

APPLICATOINS
- Scheduling eg. FIFO, Round Robin, Multilevel queue
- Maintaining Playlist 
- Interrupt Handling



In [ ]:
# implementation of linear queue
class Queue:
  def __init__(self):
    self.queue=[]
  def enqueue(self,element):
    self.queue.append(element)
  def dequeue(self):
    if len(self.queue) <1:
      return None
    return self.queue.pop(0)
  def display(self):
    print(self.queue)
  def size(self):
    return len(self.queue)

q=Queue()
q.enqueue(2)
q.enqueue(21)
q.enqueue(20)
q.enqueue(12)
q.enqueue(22)
q.display()
q.dequeue()
q.display()

[2, 21, 20, 12, 22]
[21, 20, 12, 22]


In [ ]:
# Circular Queue implementation in Python


class MyCircularQueue():

    def __init__(self, k):
        self.k = k
        self.queue = [None] * k
        self.head = self.tail = -1

    # Insert an element into the circular queue
    def enqueue(self, data):

        if ((self.tail + 1) % self.k == self.head):
            print("The circular queue is full\n")

        elif (self.head == -1):
            self.head = 0
            self.tail = 0
            self.queue[self.tail] = data
        else:
            self.tail = (self.tail + 1) % self.k
            self.queue[self.tail] = data

    # Delete an element from the circular queue
    def dequeue(self):
        if (self.head == -1):
            print("The circular queue is empty\n")

        elif (self.head == self.tail):
            temp = self.queue[self.head]
            self.head = -1
            self.tail = -1
            return temp
        else:
            temp = self.queue[self.head]
            self.head = (self.head + 1) % self.k
            return temp

    def printCQueue(self):
        if(self.head == -1):
            print("No element in the circular queue")

        elif (self.tail >= self.head):
            for i in range(self.head, self.tail + 1):
                print(self.queue[i], end=" ")
            print()
        else:
            for i in range(self.head, self.k):
                print(self.queue[i], end=" ")
            for i in range(0, self.tail + 1):
                print(self.queue[i], end=" ")
            print()


# Your MyCircularQueue object will be instantiated and called as such:
obj = MyCircularQueue(5)
obj.enqueue(1)
obj.enqueue(2)
obj.enqueue(3)
obj.enqueue(4)
obj.enqueue(5)
print("Initial queue")
obj.printCQueue()
obj.dequeue()
print("After removing an element from the queue")
obj.printCQueue()
obj.enqueue(51)
obj.printCQueue()
obj.enqueue(50)
obj.printCQueue()

Initial queue
1 2 3 4 5 
After removing an element from the queue
2 3 4 5 
2 3 4 5 51 
The circular queue is full

2 3 4 5 51 



##**Graph**
* Nodes are also called as vertices & edges are called as arcs.
* A valid graph structure consists of finite set of nodes & edges
* eg. everyone on facebook is a vertex in the network. 

A graph is a nonlinear data structure consisting of nodes and edges. The nodes are sometimes also referred to as vertices and the edges are lines or arcs that connect any two nodes in the graph. More formally a Graph can be defined as a Graph consisting of a finite set of vertices(or nodes) and a set of edges that connect a pair of nodes.

In the above Graph, the set of vertices V = {0,1,2,3,4} and the set of edges E = {01, 12, 23, 34, 04, 14, 13}. The following two are the most commonly used representations of a graph.

1.   Adjacency Matrix
2.   Adjacency List


### **Adjacency Matrix**

Adjacency Matrix is a 2D array of size V x V where V is the number of vertices in a graph. Let the 2D array be adj[][], a slot adj[i][j] = 1 indicates that there is an edge from vertex i to vertex j. The adjacency matrix for an undirected graph is always symmetric. Adjacency Matrix is also used to represent weighted graphs. If adj[i][j] = w, then there is an edge from vertex i to vertex j with weight w. 

In [ ]:
# A simple representation of graph using Adjacency Matrix
class Graph:
	def __init__(self,numvertex):
		self.adjMatrix = [[-1]*numvertex for x in range(numvertex)]
		self.numvertex = numvertex
		self.vertices = {}
		self.verticeslist =[0]*numvertex

	def set_vertex(self,vtx,id):
		if 0<=vtx<=self.numvertex:
			self.vertices[id] = vtx
			self.verticeslist[vtx] = id

	def set_edge(self,frm,to,cost=0):
		frm = self.vertices[frm]
		to = self.vertices[to]
		self.adjMatrix[frm][to] = cost
		
		# for directed graph do not add this
		self.adjMatrix[to][frm] = cost

	def get_vertex(self):
		return self.verticeslist

	def get_edges(self):
		edges=[]
		for i in range (self.numvertex):
			for j in range (self.numvertex):
				if (self.adjMatrix[i][j]!=-1):
					edges.append((self.verticeslist[i],self.verticeslist[j],self.adjMatrix[i][j]))
		return edges
		
	def get_matrix(self):
		return self.adjMatrix

G =Graph(6)
G.set_vertex(0,'a')
G.set_vertex(1,'b')
G.set_vertex(2,'c')
G.set_vertex(3,'d')
G.set_vertex(4,'e')
G.set_vertex(5,'f')
G.set_edge('a','e',10)
G.set_edge('a','c',20)
G.set_edge('c','b',30)
G.set_edge('b','e',40)
G.set_edge('e','d',50)
G.set_edge('f','e',60)

print("Vertices of Graph")
print(G.get_vertex())

print("Edges of Graph")
print(G.get_edges())

print("Adjacency Matrix of Graph")
print(G.get_matrix())


Vertices of Graph
['a', 'b', 'c', 'd', 'e', 'f']
Edges of Graph
[('a', 'c', 20), ('a', 'e', 10), ('b', 'c', 30), ('b', 'e', 40), ('c', 'a', 20), ('c', 'b', 30), ('d', 'e', 50), ('e', 'a', 10), ('e', 'b', 40), ('e', 'd', 50), ('e', 'f', 60), ('f', 'e', 60)]
Adjacency Matrix of Graph
[[-1, -1, 20, -1, 10, -1], [-1, -1, 30, -1, 40, -1], [20, 30, -1, -1, -1, -1], [-1, -1, -1, -1, 50, -1], [10, 40, -1, 50, -1, 60], [-1, -1, -1, -1, 60, -1]]


###**Adjacency List**

An array of lists is used. The size of the array is equal to the number of vertices. Let the array be an array[]. An entry array[i] represents the list of vertices adjacent to the ith vertex. This representation can also be used to represent a weighted graph. The weights of edges can be represented as lists of pairs. Following is the adjacency list representation of the above graph. 

In [ ]:
# A class to represent the adjacency list of the node
class AdjNode:
	def __init__(self, data):
		self.vertex = data
		self.next = None


# A class to represent a graph. A graph
# is the list of the adjacency lists.
# Size of the array will be the no. of the
# vertices "V"
class Graph:
	def __init__(self, vertices):
		self.V = vertices
		self.graph = [None] * self.V

	# Function to add an edge in an undirected graph
	def add_edge(self, src, dest):
	
		# Adding the node to the source node
		node = AdjNode(dest)
		node.next = self.graph[src]
		self.graph[src] = node

		# Adding the source node to the destination as
		# it is the undirected graph
		node = AdjNode(src)
		node.next = self.graph[dest]
		self.graph[dest] = node

	# Function to print the graph
	def print_graph(self):
		for i in range(self.V):
			print("Adjacency list of vertex {}\n head".format(i), end="")
			temp = self.graph[i]
			while temp:
				print(" -> {}".format(temp.vertex), end="")
				temp = temp.next
			print(" \n")


# Driver program to the above graph class
if __name__ == "__main__":
	V = 5
	graph = Graph(V)
	graph.add_edge(0, 1)
	graph.add_edge(0, 4)
	graph.add_edge(1, 2)
	graph.add_edge(1, 3)
	graph.add_edge(1, 4)
	graph.add_edge(2, 3)
	graph.add_edge(3, 4)

	graph.print_graph()


Adjacency list of vertex 0
 head -> 4 -> 1 

Adjacency list of vertex 1
 head -> 4 -> 3 -> 2 -> 0 

Adjacency list of vertex 2
 head -> 3 -> 1 

Adjacency list of vertex 3
 head -> 4 -> 2 -> 1 

Adjacency list of vertex 4
 head -> 3 -> 1 -> 0 



### **Graph Traversal**

#### **Breadth-First Search or BFS**
Breadth-First Traversal for a graph is similar to Breadth-First Traversal of a tree. The only catch here is, unlike trees, graphs may contain cycles, so we may come to the same node again. To avoid processing a node more than once, we use a boolean visited array. For simplicity, it is assumed that all vertices are reachable from the starting vertex.

For example, in the following graph, we start traversal from vertex 2. When we come to vertex 0, we look for all adjacent vertices of it. 2 is also an adjacent vertex of 0. If we don’t mark visited vertices, then 2 will be processed again and it will become a non-terminating process. A Breadth-First Traversal of the following graph is 2, 0, 3, 1.

In [ ]:
# Python3 Program to print BFS traversal
# from a given source vertex. BFS(int s)
# traverses vertices reachable from s.
from collections import defaultdict

# This class represents a directed graph
# using adjacency list representation
class Graph:

	# Constructor
	def __init__(self):

		# default dictionary to store graph
		self.graph = defaultdict(list)

	# function to add an edge to graph
	def addEdge(self,u,v):
		self.graph[u].append(v)

	# Function to print a BFS of graph
	def BFS(self, s):

		# Mark all the vertices as not visited
		visited = [False] * (max(self.graph) + 1)

		# Create a queue for BFS
		queue = []

		# Mark the source node as
		# visited and enqueue it
		queue.append(s)
		visited[s] = True

		while queue:

			# Dequeue a vertex from
			# queue and print it
			s = queue.pop(0)
			print (s, end = " ")

			# Get all adjacent vertices of the
			# dequeued vertex s. If a adjacent
			# has not been visited, then mark it
			# visited and enqueue it
			for i in self.graph[s]:
				if visited[i] == False:
					queue.append(i)
					visited[i] = True

# Driver code

# Create a graph given in
# the above diagram
g = Graph()
g.addEdge(0, 1)
g.addEdge(0, 2)
g.addEdge(1, 2)
g.addEdge(2, 0)
g.addEdge(2, 3)
g.addEdge(3, 3)

print ("Following is Breadth First Traversal"
				" (starting from vertex 2)")
g.BFS(2)


Following is Breadth First Traversal (starting from vertex 2)
2 0 3 1 

Time Complexity: O(V+E) where V is the number of vertices in the graph and E is the number of edges in the graph.

#### **Depth First Search or DFS**

Depth First Traversal for a graph is similar to Depth First Traversal of a tree. The only catch here is, unlike trees, graphs may contain cycles, a node may be visited twice. To avoid processing a node more than once, use a boolean visited array.

**Algorithm:**

Create a recursive function that takes the index of the node and a visited array.
Mark the current node as visited and print the node.
Traverse all the adjacent and unmarked nodes and call the recursive function with the index of the adjacent node.

In [ ]:
# Python3 program to print DFS traversal
# from a given given graph
from collections import defaultdict

# This class represents a directed graph using
# adjacency list representation
class Graph:

	# Constructor
	def __init__(self):

		# default dictionary to store graph
		self.graph = defaultdict(list)

	# function to add an edge to graph
	def addEdge(self, u, v):
		self.graph[u].append(v)

	# A function used by DFS
	def DFSUtil(self, v, visited):

		# Mark the current node as visited
		# and print it
		visited.add(v)
		print(v, end=' ')

		# Recur for all the vertices
		# adjacent to this vertex
		for neighbour in self.graph[v]:
			if neighbour not in visited:
				self.DFSUtil(neighbour, visited)

	# The function to do DFS traversal. It uses
	# recursive DFSUtil()
	def DFS(self, v):

		# Create a set to store visited vertices
		visited = set()

		# Call the recursive helper function
		# to print DFS traversal
		self.DFSUtil(v, visited)

# Driver code

# Create a graph given
# in the above diagram
g = Graph()
g.addEdge(0, 1)
g.addEdge(0, 2)
g.addEdge(1, 2)
g.addEdge(2, 0)
g.addEdge(2, 3)
g.addEdge(3, 3)

print("Following is DFS from (starting from vertex 2)")
g.DFS(2)


Following is DFS from (starting from vertex 2)
2 0 1 3 

##**Linked Lists**
* collection or group of node.
* each data element is connected to another one via pointers.
* python does not have linked lists in its standard library.
* implementation has to be done using lists manually.
* more efficiency for performing operation as compared to list.
* utilization of memory is higher than list.

Types of Linked List

1.   Singly Linked List
2.   Doubly Linked List 
3.   Circular Linked List



Operations

* Insertion 
** Beginning 
** at specifined node
** end

* Deletion 
** Beginning 
** at specifined node
** end

* Traversal 
** Going through each node of the linked list 

**Pseudo Code Singly Linked List**

In [ ]:
# Node class
class Node:

	# Function to initialize the node object
	def __init__(self, data):
		self.data = data # Assign data
		self.next = None # Initialize
						# next as null

# Linked List class
class LinkedList:
	
	# Function to initialize the Linked
	# List object
	def __init__(self):
		self.head = None


In [ ]:
# A simple Python program to introduce a linked list

# Node class
class Node:

	# Function to initialise the node object
	def __init__(self, data):
		self.data = data # Assign data
		self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

	# Function to initialize head
	def __init__(self):
		self.head = None


# Code execution starts here
if __name__=='__main__':

	# Start with the empty list
	llist = LinkedList()

	llist.head = Node(1)
	second = Node(2)
	third = Node(3)

	'''
	Three nodes have been created.
	We have references to these three blocks as head,
	second and third

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | None |	 | 2 | None |	 | 3 | None |
	+----+------+	 +----+------+	 +----+------+
	'''

	llist.head.next = second; # Link first node with second

	'''
	Now next of first Node refers to second. So they
	both are linked.

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | o-------->| 2 | null |	 | 3 | null |
	+----+------+	 +----+------+	 +----+------+
	'''

	second.next = third; # Link second node with the third node

	'''
	Now next of second Node refers to third. So all three
	nodes are linked.

	llist.head	 second			 third
		|			 |				 |
		|			 |				 |
	+----+------+	 +----+------+	 +----+------+
	| 1 | o-------->| 2 | o-------->| 3 | null |
	+----+------+	 +----+------+	 +----+------+
	'''


In [ ]:
# A simple Python program for traversal of a linked list

# Node class
class Node:

	# Function to initialise the node object
	def __init__(self, data):
		self.data = data # Assign data
		self.next = None # Initialize next as null


# Linked List class contains a Node object
class LinkedList:

	# Function to initialize head
	def __init__(self):
		self.head = None

	# This function prints contents of linked list
	# starting from head
	def printList(self):
		temp = self.head
		while (temp):
			print (temp.data)
			temp = temp.next


# Code execution starts here
if __name__=='__main__':

	# Start with the empty list
	llist = LinkedList()

	llist.head = Node(1)
	second = Node(2)
	third = Node(3)

	llist.head.next = second; # Link first node with second
	second.next = third; # Link second node with the third node

	llist.printList()


1
2
3


In [ ]:
class Node:
  def __init__(self,data):
    self.data=data #n1.data=8,n2.data=10,n3.data=11,n4.data=12,nb.data=3,ne.data=1,npn.data=43
    self.reference=None #all references is None here

class LinkedList:
  def __init__(self):
    self.head=None        #sll.head=None
  
  def traversal(self):
    if self.head is None:
      print("empty")
    else:
      a=self.head                   #a=sll.head
      while a is not None:          #a=sll.head=n1 #a=n1.next
        print(a.data,end=" ")       #a.data=n1.data, n2.data
        a=a.reference               #a=n1.reference, a=n2.reference
 
  def insertion_at_head(self,data): #data=8
    print()
    # insertion at head
    nb=Node(data)                   #nb=Node(8)
    nb.reference=self.head          #nb.reference=n1
    self.head=nb                    #all.head=nb
    #insertion at end

  def insertion_at_end(self,data): #data=1
    print()
    ne=Node(data)
    a=self.head                    #a=sll.head=nb
    while a.reference is not None: #a.reference=nb.reference #n1.next....n4.reference
      a=a.reference                #a=nb.reference=n1 #a=n2.........n4
    a.reference=ne                 #n4.reference=ne

  def insert_at_specified_node(self,position,data): #position=4,data=43
    print()
    npn=Node(data)
    a=self.head                   #a=sll.head=nb
    # position=int(input("enter num:"))
    for i in range(1,position-1):   #i=1
      a=a.reference                 #a=nb.reference=n1
    npn.reference=a.reference       #npn.reference=n1.reference=n2=n3
    a.reference=npn                 #a.next=n1.reference=npn

  def deletion_at_start(self):
    print()
    a=self.head
    self.head=a.reference
    a.reference=None

  def deletion_at_end(self):
    print()
    prev=self.head
    a=self.head.reference
    while a.reference is not None:
      a=a.reference
      prev=prev.reference
    prev.reference=None

  def deletion_at_specified(self,position):
    print()
    prev=self.head
    a=self.head.reference
    for i in range(1,position-1):
      a=a.reference
      prev=prev.reference
    prev.reference=a.reference
    a.reference=None


sll=LinkedList()
n1=Node(8)
sll.head=n1
n2=Node(10)
n1.reference=n2
n3=Node(11)
n2.reference=n3
n4=Node(12)
n3.reference=n4
sll.traversal()
sll.insertion_at_head(3)
sll.traversal()
sll.insertion_at_end(1)
sll.traversal()
sll.insert_at_specified_node(4,43)
sll.traversal()
sll.deletion_at_start()
sll.traversal()
sll.deletion_at_end()
sll.traversal()
sll.deletion_at_specified(3)
sll.traversal()

8 10 11 12 
3 8 10 11 12 
3 8 10 11 12 1 
3 8 10 43 11 12 1 
8 10 43 11 12 1 
8 10 43 11 12 
8 10 11 12 

**Doubly Linked List**

* A Doubly Linked List (DLL) contains an extra pointer, typically called previous pointer, together with next pointer and data which are there in singly linked list.
* Traversal is in forward as well as backward direction.

Operations

* Insertion 
** Beginning 
** at specifined node
** end

* Deletion 
** Beginning 
** at specifined node
** end

* Traversal 
** Going through each node of the linked list 


In [ ]:
# creating a node in Doubly linked list
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
    self.prev=None

# creating a class of Doubly linked list

class doublyLinkedList:
  def __init__(self):
    self.head=None

In [ ]:
class Node:
  def __init__(self,data):
    self.data=data #n1.data=8,n2.data=10,n3.data=11,n4.data=12,nb.data=3,ne.data=1,npn.data=43
    self.next=None #all references is None here
    self.prev=None #all previous is None here

class DLinkedList:
  def __init__(self):
    self.head=None        #sll.head=None
  
  def forwrd_traversal(self):
    if self.head is None:
      print("empty")
    else:
      a=self.head                   #a=sll.head
      while a is not None:          #a=sll.head=n1 #a=n1.next
        print(a.data,end=" ")       #a.data=n1.data, n2.data
        a=a.next               #a=n1.reference, a=n2.reference
 
  def backwrd_traversal(self):
    if self.head is None:
      print("empty")
    else:
      a=self.head                   #a=sll.head
      while a.next is not None:          #a=sll.head=n1 #a=n1.next
        a=a.next 
      while a is not None:
        print(a.data,end=" ")
        a=a.prev

  def insertion_at_head(self,data): #data=8
    print()
    # insertion at head
    nb=Node(data)              #nb.reference=n1
    a=self.head    
    a.prev=nb
    nb.next=a
    self.head=nb
                 

  def insertion_at_end(self,data): #data=1
    print()
    ne=Node(data)
    a=self.head                    #a=sll.head=nb
    while a.next is not None: #a.reference=nb.reference #n1.next....n4.reference
      a=a.next                #a=nb.reference=n1 #a=n2.........n4
    a.next=ne                 #n4.reference=ne
    ne.prev=a

  def insert_at_specified_node(self,position,data): #position=4,data=43
    print()
    npn=Node(data)
    a=self.head                   #a=sll.head=nb
    for i in range(1,position-1):   #i=1
      a=a.next                 #a=nb.reference=n1
    npn.next=a.next       #npn.reference=n1.reference=n2=n3
    a.next.prev=npn                 #a.next=n1.reference=npn
    npn.prev=a
    a.next=npn 

  def deletion_at_start(self):
    print()
    a=self.head
    self.head=a.next
    a.next=None
    a.prev=None

  def deletion_at_end(self):
    print()
    prev=self.head
    a=self.head.next
    while a.next is not None:
      a=a.next
      prev=prev.next
    prev.next=None
    a.prev=None

  def deletion_at_specified(self,position):
    print()
    prev=self.head
    a=self.head.next
    for i in range(1,position-1):
      a=a.next
      prev=prev.next
    prev.next=a.next
    a.prev=None
    a.next=None


dll=DLinkedList()
n1=Node(8)

dll.head=n1
n2=Node(10)
n2.prev=n1
n1.next=n2

n3=Node(11)
n3.prev=n2
n2.next=n3

n4=Node(12)
n4.prev=n3
n3.next=n4

dll.forwrd_traversal()
dll.backwrd_traversal()
dll.insertion_at_head(38)
dll.forwrd_traversal()
dll.insertion_at_end(33)
dll.forwrd_traversal()
dll.insert_at_specified_node(4,54)
dll.forwrd_traversal()
dll.deletion_at_start()
dll.forwrd_traversal()
dll.deletion_at_end()
dll.forwrd_traversal()
dll.deletion_at_specified(3)
dll.forwrd_traversal()

8 10 11 12 12 11 10 8 
38 8 10 11 12 
38 8 10 11 12 33 
38 8 10 54 11 12 33 
8 10 54 11 12 33 
8 10 54 11 12 
8 10 11 12 

##**Array**
* linear data structure.
* contiguous memory locations.
* Access elements randomly.
* homogeneous elements i.e similar elements
---
**1-D Array**
##### Why index of array strats with 0?
- arr = | 1 | 2 | 3 | 4 | 5 |
- arr =  | 0 | 1 | 2 | 3 | 4 | (index of array)
- 100-104-108-112-116 
- it gets add 4 byte in 100 at each index like
- eg. 100 + arr[0] = 100 + 0 = 100 index
- 100 + arr[3] = 100 + (3 * 4byte) = 112 index

**2-D Array**
- it can be table or matrix.
- 2 subscripts or indices are used one row & one column
- dimension depends upon the number of subscripts used.
- matrix = 3 X 4
- arr = | ! | | 0 | 1 | 2 | 3 |
- arr = | 0 | | 5 | 6 | 7 | 8 |
- arr = | 1 | | 9 | 0 | 3 | 5 | 
- arr = | 2 | | 1 | 2 | 3 | 4 |

## Array Implementation
- 1-D array Insert 
- 2-D array Insert 
- Implement search, sort & delete operaions 

In [ ]:
# 1-D array Insert

num=int(input("enter array size:"))
j=[]
for i in range(num):
  val = input("enter values:")
  j.append(val)
print(j)

enter array size:4
enter values:1
enter values:2
enter values:3
enter values:4
['1', '2', '3', '4']


In [ ]:
# 2-D array Insert

row=int(input("enter row size:"))
col=int(input("enter colunmn size:"))
j=[[0 for c in range(col)] for r in range(row)]

for r in range(row):
  for c in range(col):
    j[r][c]=r*c
print(j)


enter row size:3
enter colunmn size:2
[[0, 0], [0, 1], [0, 2]]


In [ ]:
# Delete value from array

num=int(input("enter array size:"))
arr=[]
for i in range(num):
  val=int(input("enter value:"))
  arr.append(val)

print(arr)

v1=int(input("enter num to delete"))
if v1 in arr:
  arr.remove(v1)
  print(arr)
else:
  print("enter valid number") 

enter array size:4
enter value:3
enter value:2
enter value:1
enter value:4
[3, 2, 1, 4]
enter num to delete4
[3, 2, 1]


In [ ]:
# Sorting an array

# arr=list(input("enter array:").split( ))
arr=[1,5,6,9,0]
print(arr)
for i in range(0,len(arr)):
  for j in range(i+1,len(arr)):
    if arr[i]>arr[j]:
      arr[i],arr[j]=arr[j],arr[i]

print("In ascending order:",arr)

for i in range(0,len(arr)):
  for j in range(i+1,len(arr)):
    if arr[i]<arr[j]:
      arr[i],arr[j]=arr[j],arr[i]


print("In descending order:",arr)

[1, 5, 6, 9, 0]
In ascending order: [0, 1, 5, 6, 9]
In descending order: [9, 6, 5, 1, 0]


##**Tree**
* The data originates from root node of the tree.
* Every node that procedes another node is called as the parent node.
* last node inthe tree are called as leaves

Types of trees 
1. Binary Tree
2. Binary Searched Tree

**[Binary Tree](https://www.geeksforgeeks.org/binary-tree-set-3-types-of-binary-tree/)**

* **Full Binary Tree** A Binary Tree is a full binary tree if every node has 0 or 2 children. The following are the examples of a full binary tree. We can also say a full binary tree is a binary tree in which all nodes except leaf nodes have two children. 
* **Complete Binary Tree:** A Binary Tree is a Complete Binary Tree if all the levels are completely filled except possibly the last level and the last level has all keys as left as possible.
* **Perfect Binary Tree** A Binary tree is a Perfect Binary Tree in which all the internal nodes have two children and all leaf nodes are at the same level.
* **Balanced Binary Tree** A binary tree is balanced if the height of the tree is O(Log n) where n is the number of nodes. For Example, the AVL tree maintains O(Log n) height by making sure that the difference between the heights of the left and right subtrees is at most 1. 

Tree Traversals
1. Inorder (Left, Root, Right)
2. Preorder (Root, Left, Right) 
3. Postorder (Left, Right, Root)

In [ ]:
# A Python class that represents an individual node
# in a Binary Tree
class Node:
	def __init__(self,key):
		self.left = None
		self.right = None
		self.val = key


In [ ]:
# Python program to for tree traversals

# A class that represents an individual node in a
# Binary Tree
class Node:
	def __init__(self, key):
		self.left = None
		self.right = None
		self.val = key


# A function to do inorder tree traversal
def printInorder(root):

	if root:

		# First recur on left child
		printInorder(root.left)

		# then print the data of node
		print(root.val),

		# now recur on right child
		printInorder(root.right)


# A function to do postorder tree traversal
def printPostorder(root):

	if root:

		# First recur on left child
		printPostorder(root.left)

		# the recur on right child
		printPostorder(root.right)

		# now print the data of node
		print(root.val),


# A function to do preorder tree traversal
def printPreorder(root):

	if root:

		# First print the data of node
		print(root.val),

		# Then recur on left child
		printPreorder(root.left)

		# Finally recur on right child
		printPreorder(root.right)


# Driver code
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
print("Preorder traversal of binary tree is")
printPreorder(root)

print("\nInorder traversal of binary tree is")
printInorder(root)

print("\nPostorder traversal of binary tree is")
printPostorder(root)


Preorder traversal of binary tree is
1
2
4
5
3

Inorder traversal of binary tree is
4
2
5
1
3

Postorder traversal of binary tree is
4
5
2
3
1


### Breadth-First or Level Order Traversal

Level order traversal of a tree is breadth-first traversal for the tree. The level order traversal of the above tree is 1 2 3 4 5.

For each node, first, the node is visited and then its child nodes are put in a FIFO queue. Below is the algorithm for the same –

Create an empty queue q
temp_node = root /*start from root*/
Loop while temp_node is not NULL
print temp_node->data.
Enqueue temp_node’s children (first left then right children) to q
Dequeue a node from q

In [ ]:
# Python program to print level
# order traversal using Queue

# A node structure
class Node:

	# A utility function to create a new node
	def __init__(self ,key):
		self.data = key
		self.left = None
		self.right = None

# Iterative Method to print the
# height of a binary tree
def printLevelOrder(root):

	# Base Case
	if root is None:
		return
	
	# Create an empty queue
	# for level order traversal
	queue = []

	# Enqueue Root and initialize height
	queue.append(root)

	while(len(queue) > 0):
	
		# Print front of queue and
		# remove it from queue
		print (queue[0].data)
		node = queue.pop(0)

		# Enqueue left child
		if node.left is not None:
			queue.append(node.left)

		# Enqueue right child
		if node.right is not None:
			queue.append(node.right)

# Driver Program to test above function
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)

print ("Level Order Traversal of binary tree is -")
printLevelOrder(root)


Level Order Traversal of binary tree is -
1
2
3
4
5


In [ ]:
# A utility function to search a given key in BST
def search(root,key):
	
	# Base Cases: root is null or key is present at root
	if root is None or root.val == key:
		return root

	# Key is greater than root's key
	if root.val < key:
		return search(root.right,key)

	# Key is smaller than root's key
	return search(root.left,key)


**Insertion of a key**

Start from the root.
Compare the inserting element with root, if less than root, then recurse for left, else recurse for right.
After reaching the end, just insert that node at left(if less than current) else right.

In [ ]:
# Python program to demonstrate
# insert operation in binary search tree

# A utility class that represents
# an individual node in a BST
class Node:
	def __init__(self, key):
		self.left = None
		self.right = None
		self.val = key

# A utility function to insert
# a new node with the given key
def insert(root, key):
	if root is None:
		return Node(key)
	else:
		if root.val == key:
			return root
		elif root.val < key:
			root.right = insert(root.right, key)
		else:
			root.left = insert(root.left, key)
	return root

# A utility function to do inorder tree traversal
def inorder(root):
	if root:
		inorder(root.left)
		print(root.val)
		inorder(root.right)


# Driver program to test the above functions
# Let us create the following BST
# 50
# /	 \
# 30	 70
# / \ / \
# 20 40 60 80

r = Node(50)
r = insert(r, 30)
r = insert(r, 20)
r = insert(r, 40)
r = insert(r, 70)
r = insert(r, 60)
r = insert(r, 80)

# Print inoder traversal of the BST
inorder(r)


20
30
40
50
60
70
80


## **Dynamic Programming**

Dynamic Programming is mainly an optimization over plain recursion. Wherever we see a recursive solution that has repeated calls for same inputs, we can optimize it using Dynamic Programming. The idea is to simply store the results of subproblems, so that we do not have to re-compute them when needed later. This simple optimization reduces time complexities from exponential to polynomial. For example, if we write simple recursive solution for Fibonacci Numbers, we get exponential time complexity and if we optimize it by storing solutions of subproblems, time complexity reduces to linear.



Tabulation vs Memoization
There are two different ways to store the values so that the values of a sub-problem can be reused. Here, will discuss two patterns of solving dynamic programming (DP) problem: 

Tabulation: Bottom Up
Memoization: Top Down
Tabulation
As the name itself suggests starting from the bottom and accumulating answers to the top. Let’s discuss in terms of state transition.

Let’s describe a state for our DP problem to be dp[x] with dp[0] as base state and dp[n] as our destination state. So,  we need to find the value of destination state i.e dp[n].

If we start our transition from our base state i.e dp[0] and follow our state transition relation to reach our destination state dp[n], we call it the Bottom-Up approach as it is quite clear that we started our transition from the bottom base state and reached the topmost desired state.

Now, Why do we call it tabulation method?

To know this let’s first write some code to calculate the factorial of a number using bottom up approach. Once, again as our general procedure to solve a DP we first define a state. In this case, we define a state as dp[x], where dp[x] is to find the factorial of x.

Now, it is quite obvious that dp[x+1] = dp[x] * (x+1)

```
# Tabulated version to find factorial x.
dp = [0]*MAXN

# base case
dp[0] = 1;
for i in range(n+1):
   dp[i] = dp[i-1] * i
```





**Memoization**

Once, again let’s describe it in terms of state transition. If we need to find the value for some state say dp[n] and instead of starting from the base state that i.e dp[0] we ask our answer from the states that can reach the destination state dp[n] following the state transition relation, then it is the top-down fashion of DP.

Here, we start our journey from the top most destination state and compute its answer by taking in count the values of states that can reach the destination state, till we reach the bottom-most base state.

Once again, let’s write the code for the factorial problem in the top-down fashion



```
# # Memoized version to find factorial x.
#  To speed up we store the values
# of calculated states

# initialized to -1
dp[0]*MAXN

# return fact x!
def solve(x):
   if (x==0)
       return 1
   if (dp[x]!=-1)
       return dp[x]
   return (dp[x] = x * solve(x-1))
```



# Searching Algorithms

## **Linear Search**

Start from the leftmost element of arr[] and one by one compare x with each element of arr[]
If x matches with an element, return the index.
If x doesn’t match with any of the elements, return -1.

**The time complexity of the above algorithm is O(n)**

In [ ]:
# Python3 code to linearly search x in arr[].
# If x is present then return its location,
# otherwise return -1


def search(arr, n, x):

	for i in range(0, n):
		if (arr[i] == x):
			return i
	return -1


# Driver Code
arr = [2, 3, 4, 10, 40]
x = 10
n = len(arr)

# Function call
result = search(arr, n, x)
if(result == -1):
	print("Element is not present in array")
else:
	print("Element is present at index", result)


Element is present at index 3


## **Binary Search**
Search a sorted array by repeatedly dividing the search interval in half. Begin with an interval covering the whole array. If the value of the search key is less than the item in the middle of the interval, narrow the interval to the lower half. Otherwise, narrow it to the upper half. Repeatedly check until the value is found or the interval is empty.

**The time complexity of the above algorithm is O(log(n))**. 

In [ ]:
# Python3 Program for recursive binary search.

# Returns index of x in arr if present, else -1
def binarySearch (arr, l, r, x):

	# Check base case
	if r >= l:

		mid = l + (r - l) // 2

		# If element is present at the middle itself
		if arr[mid] == x:
			return mid
		
		# If element is smaller than mid, then it
		# can only be present in left subarray
		elif arr[mid] > x:
			return binarySearch(arr, l, mid-1, x)

		# Else the element can only be present
		# in right subarray
		else:
			return binarySearch(arr, mid + 1, r, x)

	else:
		# Element is not present in the array
		return -1

# Driver Code
arr = [ 2, 3, 4, 10, 40 ]
x = 10

# Function call
result = binarySearch(arr, 0, len(arr)-1, x)

if result != -1:
	print ("Element is present at index % d" % result)
else:
	print ("Element is not present in array")


Element is present at index  3


# Sorting Algorithms

##Selection Sort

The selection sort algorithm sorts an array by repeatedly finding the minimum element (considering ascending order) from unsorted part and putting it at the beginning. In every iteration of selection sort, the minimum element (considering ascending order) from the unsorted subarray is picked and moved to the sorted subarray. 




1.   **Time Complexity: O(n2)** as there are two nested loops.

2.   **Auxiliary Space: O(1)** 



In [ ]:
# Python program for implementation of Selection
# Sort
import sys


A = [64, 25, 12, 22, 11]

# Traverse through all array elements
for i in range(len(A)):
	
	# Find the minimum element in remaining
	# unsorted array
	min_idx = i
	for j in range(i+1, len(A)):
		if A[min_idx] > A[j]:
			min_idx = j
			
	# Swap the found minimum element with
	# the first element
	A[i], A[min_idx] = A[min_idx], A[i]

# Driver code to test above
print ("Sorted array")
for i in range(len(A)):
	print("%d" %A[i]),


Sorted array
11
12
22
25
64


## Bubble Sort
Bubble Sort is the simplest sorting algorithm that works by repeatedly swapping the adjacent elements if they are in wrong order.

**Time Complexity: O(n2)**

In [ ]:
# Python program for implementation of Bubble Sort

def bubbleSort(arr):
	n = len(arr)

	# Traverse through all array elements
	for i in range(n):

		# Last i elements are already in place
		for j in range(0, n-i-1):

			# traverse the array from 0 to n-i-1
			# Swap if the element found is greater
			# than the next element
			if arr[j] > arr[j+1] :
				arr[j], arr[j+1] = arr[j+1], arr[j]

# Driver code to test above
arr = [64, 34, 25, 12, 22, 11, 90]

bubbleSort(arr)

print ("Sorted array is:")
for i in range(len(arr)):
	print ("%d" %arr[i]),


Sorted array is:
11
12
22
25
34
64
90


## Insertion Sort
To sort an array of size n in ascending order using insertion sort:

Iterate from arr[1] to arr[n] over the array.
Compare the current element (key) to its predecessor.
If the key element is smaller than its predecessor, compare it to the elements before. Move the greater elements one position up to make space for the swapped element.

**Time Complexity: O(n2))**

In [ ]:
# Python program for implementation of Insertion Sort

# Function to do insertion sort
def insertionSort(arr):

	# Traverse through 1 to len(arr)
	for i in range(1, len(arr)):

		key = arr[i]

		# Move elements of arr[0..i-1], that are
		# greater than key, to one position ahead
		# of their current position
		j = i-1
		while j >= 0 and key < arr[j] :
				arr[j + 1] = arr[j]
				j -= 1
		arr[j + 1] = key


# Driver code to test above
arr = [12, 11, 13, 5, 6]
insertionSort(arr)
for i in range(len(arr)):
	print ("% d" % arr[i])


 5
 6
 11
 12
 13


## Merge Sort
Like QuickSort, Merge Sort is a Divide and Conquer algorithm. It divides the input array into two halves, calls itself for the two halves, and then merges the two sorted halves. The merge() function is used for merging two halves. The merge(arr, l, m, r) is a key process that assumes that arr[l..m] and arr[m+1..r] are sorted and merges the two sorted sub-arrays into one. 
```
MergeSort(arr[], l,  r)
If r > l
     1. Find the middle point to divide the array into two halves:  
             middle m = l+ (r-l)/2
     2. Call mergeSort for first half:   
             Call mergeSort(arr, l, m)
     3. Call mergeSort for second half:
             Call mergeSort(arr, m+1, r)
     4. Merge the two halves sorted in step 2 and 3:
             Call merge(arr, l, m, r)


```

**Time Complexity: O(n(logn))**

In [ ]:
# Python program for implementation of MergeSort
def mergeSort(arr):
	if len(arr) > 1:

		# Finding the mid of the array
		mid = len(arr)//2

		# Dividing the array elements
		L = arr[:mid]

		# into 2 halves
		R = arr[mid:]

		# Sorting the first half
		mergeSort(L)

		# Sorting the second half
		mergeSort(R)

		i = j = k = 0

		# Copy data to temp arrays L[] and R[]
		while i < len(L) and j < len(R):
			if L[i] < R[j]:
				arr[k] = L[i]
				i += 1
			else:
				arr[k] = R[j]
				j += 1
			k += 1

		# Checking if any element was left
		while i < len(L):
			arr[k] = L[i]
			i += 1
			k += 1

		while j < len(R):
			arr[k] = R[j]
			j += 1
			k += 1

# Code to print the list


def printList(arr):
	for i in range(len(arr)):
		print(arr[i], end=" ")
	print()


# Driver Code
if __name__ == '__main__':
	arr = [12, 11, 13, 5, 6, 7]
	print("Given array is", end="\n")
	printList(arr)
	mergeSort(arr)
	print("Sorted array is: ", end="\n")
	printList(arr)


Given array is
12 11 13 5 6 7 
Sorted array is: 
5 6 7 11 12 13 


## QuickSort
Like Merge Sort, QuickSort is a Divide and Conquer algorithm. It picks an element as pivot and partitions the given array around the picked pivot. There are many different versions of quickSort that pick pivot in different ways.

Always pick first element as pivot.

Always pick last element as pivot (implemented below)
Pick a random element as pivot.
Pick median as pivot.
The key process in quickSort is partition(). Target of partitions is, given an array and an element x of array as pivot, put x at its correct position in sorted array and put all smaller elements (smaller than x) before x, and put all greater elements (greater than x) after x. All this should be done in linear time.


```
/* low  --> Starting index,  high  --> Ending index */
quickSort(arr[], low, high)
{
    if (low < high)
    {
        /* pi is partitioning index, arr[pi] is now
           at right place */
        pi = partition(arr, low, high);

        quickSort(arr, low, pi - 1);  // Before pi
        quickSort(arr, pi + 1, high); // After pi
    }
}

```

## Partition Algorithm

There can be many ways to do partition, following pseudo code adopts the method given in CLRS book. The logic is simple, we start from the leftmost element and keep track of index of smaller (or equal to) elements as i. While traversing, if we find a smaller element, we swap current element with arr[i]. Otherwise we ignore current element. 



```
/* low  --> Starting index,  high  --> Ending index */
quickSort(arr[], low, high)
{
    if (low < high)
    {
        /* pi is partitioning index, arr[pi] is now
           at right place */
        pi = partition(arr, low, high);

        quickSort(arr, low, pi - 1);  // Before pi
        quickSort(arr, pi + 1, high); // After pi
    }
}
```



## ShellSort
ShellSort is mainly a variation of Insertion Sort. In insertion sort, we move elements only one position ahead. When an element has to be moved far ahead, many movements are involved. The idea of shellSort is to allow the exchange of far items. In shellSort, we make the array h-sorted for a large value of h. We keep reducing the value of h until it becomes 1. An array is said to be h-sorted if all sublists of every hth element is sorted.

**Time Complexity:  O(n2)**

In [ ]:
# Python3 program for implementation of Shell Sort

def shellSort(arr):
	gap = len(arr) // 2 # initialize the gap

	while gap > 0:
		i = 0
		j = gap
		
		# check the array in from left to right
		# till the last possible index of j
		while j < len(arr):
	
			if arr[i] >arr[j]:
				arr[i],arr[j] = arr[j],arr[i]
			
			i += 1
			j += 1
		
			# now, we look back from ith index to the left
			# we swap the values which are not in the right order.
			k = i
			while k - gap > -1:

				if arr[k - gap] > arr[k]:
					arr[k-gap],arr[k] = arr[k],arr[k-gap]
				k -= 1

		gap //= 2


# driver to check the code
arr2 = [12, 34, 54, 2, 3]
print("input array:",arr2)

shellSort(arr2)
print("sorted array",arr2)


input array: [12, 34, 54, 2, 3]
sorted array [2, 3, 12, 34, 54]


#Common Asymptotic Notations
A list of some common asymptotic notations is mentioned below −

* constant	−	Ο(1)
* logarithmic	−	Ο(log n)
* linear	−	Ο(n)
* n log n	−	Ο(n log n)
* quadratic	−	Ο(n2)
* cubic	−	Ο(n3)
* polynomial	−	nΟ(1)
* exponential	−	2Ο(n)

**Refrence**



1.   https://www.geeksforgeeks.org/python-data-structures-and-algorithms/
2.   https://www.youtube.com/watch?v=MLqHDsBOC4c
3.   https://www.tutorialspoint.com/python_data_structure/python_big_o_notation.htm


